### ISSUE TITLE
Space for a "who's using swarm"?

### ISSUE THREAD

**Issue by decentral1se** [BretFisher/awesome-swarm#11]
E.g. our project https://coopcloud.tech makes uses of swarm mode.

We have some related docs also https://docs.coopcloud.tech/intro/faq/#why-docker-swarm

**Comment by s4ke** [comment]
I think having a section like this could be a good idea as it shows the existing communities that make use of Swarm.

A downside of this could be that we have to re-check whether the companies/organisations are alive every once in a while, but for now, I think we should try it.

wdyt @BretFisher ?

**Comment by BretFisher** [comment]
YES! @decentral1se, please make a PR for us to start adding "Organizations Using Swarm" below the tool list thanks!
