### ISSUE TITLE
Compose Examples

### ISSUE THREAD

**Issue by s4ke** [BretFisher/awesome-swarm#20]
Should we add https://github.com/Haxxnet/Compose-Examples ?

This is not specifically for Swarm, but could be helpful to people to get started with a new stack.

**Comment by BretFisher** [comment]
Since there's already an Awesome Compose, and this has the feeling of "if we add compose stuff, where will it end?"

I think it makes more sense to:

1. Add a new section to this repo: "related awesome lists":
    2. https://github.com/veggiemonk/awesome-docker
    3. https://github.com/docker/awesome-compose
4. PR that compose examples list to awesome compose if not already there.

WDYT?

**Comment by BretFisher** [comment]
Fixed by #21
