### ISSUE TITLE
Decide how to handle subprojects

### ISSUE THREAD

**Issue by s4ke** [BretFisher/awesome-swarm#7]
**Description**

We should decide on how to handle subprojects of the things we put on this list. Should we only list the main project here, or should we be able to list more subprojects if they are interesting in their own regard?

**Background:**

We are maintaining swarmsible with some sub projects that build on top of it. One of them is https://github.com/neuroforgede/swarmsible-hetzner which is essentially "one-click-cluster-setup"-tooling for Docker Swarm on Hetzner. Should such projects be in this list or should the respective projects just link to the subprojects?

**Comment by BretFisher** [comment]
Both are fine. If you think they deserve their own item in list, fine. If you think it's just worth mentioning in the description, fine too.  Feel free to browse other [Awesome Lists](https://github.com/sindresorhus/awesome) for inspiration and guidance.
