### ISSUE TITLE
Decide how to handle Cloud Vendor specific plugins/drivers

### ISSUE THREAD

**Issue by s4ke** [BretFisher/awesome-swarm#8]
**Description**

We should decide how to keep track of cloud vendor specific things, such as Volume drivers. Should they live in their own section?

**Background**

I was thinking about adding https://github.com/costela/docker-volume-hetzner especially while the CSI support is not ironclad, but this is specific to one cloud vendor - Hetzner.

**Comment by BretFisher** [comment]
Totally, under Volumes and Storage. Anything that can be used by Swarm somehow. I just noticed that CoPilot filled in the descriptions for GlusterFS and Ceph (which I don't even know if they work with Swarm currently), lol.

**Comment by s4ke** [comment]
I think ceph and gluster are fine

**Comment by s4ke** [comment]
See https://geek-cookbook.funkypenguin.co.nz/docker-swarm/shared-storage-ceph/ (this Blog should be added anyways)
